import { IMyWhoIs } from "@/types";

export const initialMyWhoIs: IMyWhoIs = {
  "Admin City": "",
  "Admin Country": "",
  "Admin Email": "",
  "Admin Fax": "",
  "Admin Fax Ext": "",
  "Admin Name": "",
  "Admin Organization": "",
  "Admin Phone": "",
  "Admin Phone Ext": "",
  "Admin Postal Code": "",
  "Admin State/Province": "",
  "Admin Street": "",
  "Contact information available here": "",
  DNSSEC: "",
  "Domain Name": "",
  "For more information on Whois status codes, please visit https": "",
  "Name Server": [],
  "Registrant City": "",
  "Registrant Country": "",
  "Registrant Email": "",
  "Registrant Fax": "",
  "Registrant Fax Ext": "",
  "Registrant Name": "",
  "Registrant Organization": "",
  "Registrant Phone": "",
  "Registrant Phone Ext": "",
  "Registrant Postal Code": "",
  "Registrant State/Province": "",
  "Registrant Street": "",
  Registrar: "",
  "Registrar Abuse Contact Email": "",
  "Registrar Abuse Contact Phone": "",
  "Registrar IANA ID": "",
  "Registrar WHOIS Server": "",
  "Registry Admin ID": "",
  "Registry Domain ID": "",
  "Registry Registrant ID": "",
  "Registry Tech ID": "",
  "Tech City": "",
  "Tech Country": "",
  "Tech Email": "",
  "Tech Fax": "",
  "Tech Fax Ext": "",
  "Tech Name": "",
  "Tech Organization": "",
  "Tech Phone": "",
  "Tech Phone Ext": "",
  "Tech Postal Code": "",
  "Tech State/Province": "",
  "Tech Street": "",
  "Visit Amazon Registrar, Inc. at https": "",
  "data for any unlawful purpose or to": "",
  https: "",
};
