import { IWhoIs } from "@/types";

export const initialWhoIs: IWhoIs = {
  WhoisRecord: {
    administrativeContact: {
      city: "",
      country: "",
      countryCode: "",
      email: "",
      fax: "",
      name: "",
      organization: "",
      postalCode: "",
      rawText: "",
      state: "",
      street1: "",
      telephone: "",
    },
    audit: {
      createdDate: "",
      updatedDate: "",
    },
    contactEmail: "",
    createdDate: "",
    createdDateNormalized: "",
    domainName: "",
    domainNameExt: "",
    estimatedDomainAge: 0,
    expiresDate: "",
    expiresDateNormalized: "",
    footer: "",
    header: "",
    nameServers: {
      hostNames: [],
      ips: [],
      rawText: "",
    },
    parseCode: 0,
    rawText: "",
    registrant: {
      city: "",
      country: "",
      countryCode: "",
      email: "",
      fax: "",
      name: "",
      organization: "",
      postalCode: "",
      rawText: "",
      state: "",
      street1: "",
      telephone: "",
    },
    registrarIANAID: "",
    registrarName: "",
    registryData: {
      audit: {
        createdDate: "",
        updatedDate: "",
      },
      createdDate: new Date(),
      createdDateNormalized: "",
      domainName: "",
      expiresDate: new Date(),
      expiresDateNormalized: "",
      footer: "",
      header: "",
      nameServers: {
        hostNames: [],
        ips: [],
        rawText: "",
      },
      parseCode: 0,
      rawText: "",
      registrarIANAID: "",
      registrarName: "",
      status: "",
      strippedText: "",
      updatedDate: new Date(),
      updatedDateNormalized: "",
      whoisServer: "",
    },
    status: "",
    strippedText: "",
    technicalContact: {
      city: "",
      country: "",
      countryCode: "",
      email: "",
      fax: "",
      name: "",
      organization: "",
      postalCode: "",
      rawText: "",
      state: "",
      street1: "",
      telephone: "",
    },
    updatedDate: new Date(),
    updatedDateNormalized: "",
  },
};
