export interface IMyWhoIs {
  "Admin City": string;
  "Admin Country": string;
  "Admin Email": string;
  "Admin Fax": string;
  "Admin Fax Ext": string;
  "Admin Name": string;
  "Admin Organization": string;
  "Admin Phone": string;
  "Admin Phone Ext": string;
  "Admin Postal Code": string;
  "Admin State/Province": string;
  "Admin Street": string;
  "Contact information available here": string;
  DNSSEC: string;
  "Domain Name": string;
  "For more information on Whois status codes, please visit https": string;
  "Name Server": string[];
  "Registrant City": string;
  "Registrant Country": string;
  "Registrant Email": string;
  "Registrant Fax": string;
  "Registrant Fax Ext": string;
  "Registrant Name": string;
  "Registrant Organization": string;
  "Registrant Phone": string;
  "Registrant Phone Ext": string;
  "Registrant Postal Code": string;
  "Registrant State/Province": string;
  "Registrant Street": string;
  Registrar: string;
  "Registrar Abuse Contact Email": string;
  "Registrar Abuse Contact Phone": string;
  "Registrar IANA ID": string;
  "Registrar WHOIS Server": string;
  "Registry Admin ID": string;
  "Registry Domain ID": string;
  "Registry Registrant ID": string;
  "Registry Tech ID": string;
  "Tech City": string;
  "Tech Country": string;
  "Tech Email": string;
  "Tech Fax": string;
  "Tech Fax Ext": string;
  "Tech Name": string;
  "Tech Organization": string;
  "Tech Phone": string;
  "Tech Phone Ext": string;
  "Tech Postal Code": string;
  "Tech State/Province": string;
  "Tech Street": string;
  "Visit Amazon Registrar, Inc. at https": string;
  "data for any unlawful purpose or to": string;
  https: string;
}
